// <auto-generated />
namespace Hei10.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StevenUpdateMarket1201 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StevenUpdateMarket1201));
        
        string IMigrationMetadata.Id
        {
            get { return "201612010615274_StevenUpdateMarket1201"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
