// <auto-generated />
namespace Hei10.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class StevenInitDB1130 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StevenInitDB1130));
        
        string IMigrationMetadata.Id
        {
            get { return "201611300705240_StevenInitDB1130"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
